name: Run Mobile Tests - Appium + Sourcelabs

on:
  push:
    branches: [ci]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Setting Enviroments
        run: |
          echo "PLATFORM=${{ vars.PLATFORM }}" >> $GITHUB_ENV
          echo "ENVIRONMENT=${{ vars.ENVIRONMENT }}" >> $GITHUB_ENV
          echo "REPORT=${{ vars.REPORT }}" >> $GITHUB_ENV
          echo "SAUCE_USERNAME=${{ secrets.SAUCE_USERNAME }}" >> $GITHUB_ENV
          echo "SAUCE_ACCESS_KEY=${{ secrets.SAUCE_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm i
      - name: Run Tests
        run: npm run mobile-test
      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.ACTIONS_PAT }}
          publish_dir: ./allure-report
